//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schiduch.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Schiduch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;he&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;title&gt;דו&quot;ח&lt;/title&gt;
        ///  &lt;meta charset=&quot;utf-8&quot;&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///&lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html;charset=iso-8859-8-i&quot;&gt;
        ///  &lt;link rel=&quot;stylesheet&quot; href=&quot;http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css&quot;&gt;
        ///  &lt;script src=&quot;https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.mi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnotherReportHeader {
            get {
                return ResourceManager.GetString("AnotherReportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;he&quot;&gt;
        ///&lt;head&gt;
        ///
        ///&lt;style&gt;
        ///body {background-image:url(&apos;file:///bg.jpg&apos;); padding-top:30px; }
        ///.round { background-color:#5ba6e7; -webkit-border-radius: 4px; -moz-border-radius: 4px; border-radius: 4px; }
        ///.time { 
        ///    font-size: 8px;
        ///    color: gray;
        ///    margin: 0px;
        ///    text-align: left;
        ///    padding-top: 6px;}
        ///.time2 { float:left; padding-left:0px; color:#000; font-weight:600;}
        ///
        ///.personName { float:right;position:absolute;left:45%; padding-left:0px; color:#5586e5; font-we [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChatWeb {
            get {
                return ResourceManager.GetString("ChatWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;hr&gt;&lt;u&gt;&lt;h2&gt;סך הכל&lt;/h2&gt;&lt;/u&gt;&lt;table class=&apos;table table-bordered&apos;&gt;&lt;thead&gt;&lt;tr&gt;
        ///        &lt;th style=&apos;text-align:right&apos;&gt;שדכן&lt;/th&gt;
        ///        &lt;th style=&apos;text-align:right&apos;&gt;פתח כרטיס לקוח&lt;/th&gt;
        ///        &lt;th style=&apos;text-align:right&apos;&gt;בדק מה הטלפון&lt;/th&gt;
        ///        &lt;th style=&apos;text-align:right&apos;&gt;התקשר ולא ענו&lt;/th&gt;
        ///        &lt;th style=&apos;text-align:right&apos;&gt;התקשרו והציעו&lt;/th&gt;
        ///        &lt;th style=&apos;text-align:right&apos;&gt;התקשרו הציעו ולא יצא&lt;/th&gt;        &lt;th style=&apos;text-align:right&apos;&gt;התקשרו לפגישה&lt;/th&gt;
        ///      &lt;/tr&gt;
        ///    &lt;/thead&gt;
        ///    &lt;tbody&gt;.
        /// </summary>
        internal static string ClientSumTableHeaders {
            get {
                return ResourceManager.GetString("ClientSumTableHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ClientTableHeader {
            get {
                return ResourceManager.GetString("ClientTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap construction_firm_icon {
            get {
                object obj = ResourceManager.GetObject("construction-firm-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/div&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string ReportEnd {
            get {
                return ResourceManager.GetString("ReportEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;he&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;title&gt;דו&quot;ח&lt;/title&gt;
        ///  &lt;meta charset=&quot;utf-8&quot;&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///&lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html;charset=iso-8859-8-i&quot;&gt;
        ///  &lt;link rel=&quot;stylesheet&quot; href=&quot;http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css&quot;&gt;
        ///  &lt;script src=&quot;https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.mi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReportHeader {
            get {
                return ResourceManager.GetString("ReportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/tbody&gt;
        ///    &lt;/table&gt;
        ///    &lt;/div&gt; &lt;div class=&quot;col-sm-12&quot; style=&quot;float:right&quot;&gt;.
        /// </summary>
        internal static string ShadchanStartDatesFooter {
            get {
                return ResourceManager.GetString("ShadchanStartDatesFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;col-sm-12&quot; style=&quot;float:right&quot;&gt;
        ///  &lt;table  class=&quot;table&quot;&gt;
        ///    &lt;thead&gt;
        ///      &lt;tr&gt;
        ///        &lt;th class=&quot;text-right&quot;&gt;לקוח&lt;/th&gt;
        ///        &lt;th class=&quot;text-right&quot;&gt;שדכן&lt;/th&gt;
        ///        &lt;th class=&quot;text-right&quot;&gt;בתאריך&lt;/th&gt;
        ///         &lt;/thead&gt;
        ///    &lt;tbody&gt;.
        /// </summary>
        internal static string ShadchanStartDatesHeader {
            get {
                return ResourceManager.GetString("ShadchanStartDatesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap לוגו_שנתבשר {
            get {
                object obj = ResourceManager.GetObject("לוגו שנתבשר", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
